// <auto-generated />
using System;
using Company.AutomationOfThePurchasingActOfRestaurant.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Company.AutomationOfThePurchasingActOfRestaurant.Context.Migrations
{
    [DbContext(typeof(PurchasingContext))]
    partial class PurchasingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Approver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfDeletion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfLastChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelited")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SignatureId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Approver");
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfDeletion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfLastChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelited")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.EmployeePosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfDeletion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfLastChange")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelited")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployeePosition");
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.FormKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfDeletion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfLastChange")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelited")
                        .HasColumnType("bit");

                    b.Property<string>("OKDP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OKPO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OKUD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PurchaseFormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FormKey");
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.MeasurementUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfDeletion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfLastChange")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelited")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OKEIKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MeasurementUnit");
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Merchandise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfDeletion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfLastChange")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelited")
                        .HasColumnType("bit");

                    b.Property<Guid>("MeasurementUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MerchandiseKey")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementUnitId");

                    b.ToTable("Merchandise");
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.MerchandisePrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CostPerUnit")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfDeletion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfLastChange")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelited")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MerchandiseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MerchandiseId");

                    b.ToTable("MerchandisePrice");
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfDeletion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfLastChange")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelited")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StructuralUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organization");
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.PurchaseForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressOfPurchase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ApprovingOfficerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfDeletion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfLastChange")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("FormKeyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelited")
                        .HasColumnType("bit");

                    b.Property<Guid>("OfficerSignatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProcurementSpecialistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SalesmanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SponsorOrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApprovingOfficerId");

                    b.HasIndex("FormKeyId")
                        .IsUnique();

                    b.HasIndex("OfficerSignatureId");

                    b.HasIndex("ProcurementSpecialistId");

                    b.HasIndex("SalesmanId");

                    b.HasIndex("SponsorOrganizationId");

                    b.ToTable("PurchaseForm");
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Signature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApproverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfDeletion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfLastChange")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelited")
                        .HasColumnType("bit");

                    b.Property<string>("Points")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureDecryption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId")
                        .IsUnique()
                        .HasFilter("[ApproverId] IS NOT NULL");

                    b.ToTable("Signature");
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfDeletion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfLastChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelited")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("MerchandisePricePurchaseForm", b =>
                {
                    b.Property<Guid>("PricesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PurchaseFormsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PricesId", "PurchaseFormsId");

                    b.HasIndex("PurchaseFormsId");

                    b.ToTable("MerchandisePricePurchaseForm");
                });

            modelBuilder.Entity("MerchandisePurchaseForm", b =>
                {
                    b.Property<Guid>("PurchaseFormsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PurchasedMerchandisesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PurchaseFormsId", "PurchasedMerchandisesId");

                    b.HasIndex("PurchasedMerchandisesId");

                    b.ToTable("MerchandisePurchaseForm");
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Approver", b =>
                {
                    b.HasOne("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.EmployeePosition", "Position")
                        .WithMany("Approvers")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Employee", b =>
                {
                    b.HasOne("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.EmployeePosition", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Merchandise", b =>
                {
                    b.HasOne("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.MeasurementUnit", "MeasurementUnit")
                        .WithMany("Merchandises")
                        .HasForeignKey("MeasurementUnitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MeasurementUnit");
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.MerchandisePrice", b =>
                {
                    b.HasOne("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Merchandise", "Merchandise")
                        .WithMany("Prices")
                        .HasForeignKey("MerchandiseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Merchandise");
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.PurchaseForm", b =>
                {
                    b.HasOne("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Approver", "ApprovingOfficer")
                        .WithMany("PurchaseForms")
                        .HasForeignKey("ApprovingOfficerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.FormKey", "FormKey")
                        .WithOne("PurchaseForm")
                        .HasForeignKey("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.PurchaseForm", "FormKeyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Signature", "OfficerSignature")
                        .WithMany("purchaseForms")
                        .HasForeignKey("OfficerSignatureId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Employee", "ProcurementSpecialist")
                        .WithMany("PurchaseForms")
                        .HasForeignKey("ProcurementSpecialistId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Supplier", "Salesman")
                        .WithMany("PurchaseForms")
                        .HasForeignKey("SalesmanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Organization", "SponsorOrganization")
                        .WithMany("PurchaseForms")
                        .HasForeignKey("SponsorOrganizationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApprovingOfficer");

                    b.Navigation("FormKey");

                    b.Navigation("OfficerSignature");

                    b.Navigation("ProcurementSpecialist");

                    b.Navigation("Salesman");

                    b.Navigation("SponsorOrganization");
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Signature", b =>
                {
                    b.HasOne("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Approver", "Approver")
                        .WithOne("Signature")
                        .HasForeignKey("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Signature", "ApproverId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Approver");
                });

            modelBuilder.Entity("MerchandisePricePurchaseForm", b =>
                {
                    b.HasOne("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.MerchandisePrice", null)
                        .WithMany()
                        .HasForeignKey("PricesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.PurchaseForm", null)
                        .WithMany()
                        .HasForeignKey("PurchaseFormsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MerchandisePurchaseForm", b =>
                {
                    b.HasOne("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.PurchaseForm", null)
                        .WithMany()
                        .HasForeignKey("PurchaseFormsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Merchandise", null)
                        .WithMany()
                        .HasForeignKey("PurchasedMerchandisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Approver", b =>
                {
                    b.Navigation("PurchaseForms");

                    b.Navigation("Signature")
                        .IsRequired();
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Employee", b =>
                {
                    b.Navigation("PurchaseForms");
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.EmployeePosition", b =>
                {
                    b.Navigation("Approvers");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.FormKey", b =>
                {
                    b.Navigation("PurchaseForm");
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.MeasurementUnit", b =>
                {
                    b.Navigation("Merchandises");
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Merchandise", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Organization", b =>
                {
                    b.Navigation("PurchaseForms");
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Signature", b =>
                {
                    b.Navigation("purchaseForms");
                });

            modelBuilder.Entity("Company.AutomationOfThePurchasingActOfRestaurant.Context.Contracts.Models.Supplier", b =>
                {
                    b.Navigation("PurchaseForms");
                });
#pragma warning restore 612, 618
        }
    }
}
